MODULE KNN
    USE IRIS_DATA
    IMPLICIT NONE
    CONTAINS
    FUNCTION EUCLIDEAN_DISTANCE(POINT_1, POINT_2) RESULT(DISTANCE)
        IMPLICIT NONE
        TYPE(IRIS_RECORD), INTENT(IN) :: POINT_1, POINT_2
        REAL(KIND = 8) :: DISTANCE, PARTIAL_DISTANCE = 0

        PARTIAL_DISTANCE = PARTIAL_DISTANCE + (POINT_1%SEPAL_LENGTH - POINT_2%SEPAL_LENGTH) ** 2
        PARTIAL_DISTANCE = PARTIAL_DISTANCE + (POINT_1%SEPAL_WIDTH - POINT_2%SEPAL_WIDTH) ** 2
        PARTIAL_DISTANCE = PARTIAL_DISTANCE + (POINT_1%PETAL_LENGTH - POINT_2%PETAL_LENGTH) ** 2
        PARTIAL_DISTANCE = PARTIAL_DISTANCE + (POINT_1%PETAL_WIDTH - POINT_2%PETAL_WIDTH) ** 2

        DISTANCE = PARTIAL_DISTANCE

    END FUNCTION EUCLIDEAN_DISTANCE

    SUBROUTINE SORT_ARRAY(LIST)
        IMPLICIT NONE
        TYPE(TUPLE), DIMENSION(200), INTENT(INOUT):: LIST
        TYPE(TUPLE) :: SWAP_AUX
        INTEGER :: I = 1, K

        DO I = 2, SIZE(LIST)
            K = I - 1
            SWAP_AUX = LIST(I)
            DO WHILE (K .LE. 1 .AND. (LIST(K)%DISTANCE .GT. SWAP_AUX%DISTANCE))
                LIST(K + 1) = LIST(K)
                K = K - 1
            END DO
            LIST(K + 1) = SWAP_AUX
        END DO
        
    END SUBROUTINE SORT_ARRAY

    FUNCTION MEAN(LABELS) RESULT(PREDICTION)
        IMPLICIT NONE
        REAL, DIMENSION(:), INTENT(IN) :: LABELS
        REAL :: PREDICTION, PARTIAL_PREDICTION = 0
        INTEGER :: LABELS_SIZE, I = 1
        
        LABELS_SIZE = SIZE(LABELS)

     20 CONTINUE
        IF (I .LE. LABELS_SIZE) THEN
            PARTIAL_PREDICTION = PARTIAL_PREDICTION + LABELS(I)
            GOTO 20
        END IF

        PREDICTION = PARTIAL_PREDICTION / LABELS_SIZE
    END FUNCTION MEAN

    FUNCTION FIND_K_NEAREST_NEIGHBOR(QUERY, K) RESULT(K_NEIGHBOR)
        IMPLICIT NONE
        INTEGER :: K, IO, I = 1
        TYPE(TUPLE) :: NEIGHBOR
        TYPE(TUPLE), DIMENSION(200) :: DISTANCES
        TYPE(TUPLE), DIMENSION(K) :: K_NEIGHBOR
        TYPE(IRIS_RECORD_LIST) :: IRIS_INSTANCES
        TYPE(IRIS_RECORD) :: CURRENT_RECORD, QUERY

        OPEN(UNIT=18, FILE='./../iris.data', STATUS='OLD', ACCESS='SEQUENTIAL', FORM='FORMATTED', RECL=1)
     30 CONTINUE   
        READ(UNIT=18, FMT=*, IOSTAT=IO) CURRENT_RECORD
        IF (IO .LT. 0) GOTO 40
        CALL APPEND(IRIS_INSTANCES, CURRENT_RECORD)
        GOTO 30
     40 CLOSE(18)

     50 CONTINUE
        IF (I .LE. IRIS_INSTANCES%LENGTH) THEN
            CURRENT_RECORD = FIND_ELEMENT(IRIS_INSTANCES, I)
            NEIGHBOR%INDEX = I
            NEIGHBOR%DISTANCE = EUCLIDEAN_DISTANCE(CURRENT_RECORD, QUERY)
            NEIGHBOR%VALUE = CURRENT_RECORD
            DISTANCES(I) = NEIGHBOR
            I = I + 1
            GOTO 50
        END IF

        CALL SORT_ARRAY(DISTANCES)

        I = 1
     60 CONTINUE
        IF (I .LE. K) THEN
            K_NEIGHBOR(I) = DISTANCES(I)
            PRINT *, K_NEIGHBOR(I)
            I = I + 1
            GOTO 60
        END IF
    END FUNCTION FIND_K_NEAREST_NEIGHBOR
END MODULE KNN