PROGRAM MAIN
    USE KNN
    IMPLICIT NONE
    TYPE(TUPLE), DIMENSION(3) :: K_NEIGHBOR
    TYPE(IRIS_RECORD) :: QUERY

    QUERY%SEPAL_LENGTH = 4.8
    QUERY%SEPAL_WIDTH = 3.0
    QUERY%PETAL_LENGTH = 1.4
    QUERY%PETAL_WIDTH = 0.1
    QUERY%CLASS = ''

    K_NEIGHBOR = FIND_K_NEAREST_NEIGHBOR(QUERY, 3)
    PRINT *, K_NEIGHBOR(1)
    
END PROGRAM MAIN
